# Generated by Django 4.2.2 on 2023-09-03 01:53

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_videoupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to='post_images/')),
                ('file', models.FileField(upload_to='posts_videos/')),
                ('captions', models.TextField(max_length=200)),
                ('no_of_likes', models.IntegerField(default=0)),
                ('date_of_upload', models.TimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
