# Generated by Django 4.2.2 on 2023-09-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_remove_post_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profolieImg',
            new_name='proflieImg',
        ),
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to='mainApp.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='mainApp.profile'),
        ),
    ]
