# Generated by Django 4.2.2 on 2023-09-10 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_rename_user_post_uploader'),
    ]

    operations = [
    ]
