# Generated by Django 4.2.2 on 2023-09-11 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_auto_20230910_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='uploader',
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainApp.profile'),
        ),
    ]
